### ISSUE TITLE
[ossia-pd] ø.client add connect with device name

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#106]
and a get message to list available devices on the network

**Comment by bltzr** [comment]
ossia.client: no method for 'get'

**Comment by bltzr** [comment]
OK, so that's [find_devices( instead of [get(

**Comment by bltzr** [comment]
maybe there's a potential confusion coming from the fact that connect can be followed indifferently from a protocol or a device name 
Is that OK ? if it is, it should be documented in the console when pressing [connect(
If it's not, then we should find some syntactic differentiation...

**Comment by avilleret** [comment]
actually default port and IP was initially to quickly test and setup ossia-pd
I know this is confusing that `connect` message could be followed by either a device name or a protocol name and since Minuit protocol seems to be deprecated, I suggest to remove the [connect <protocolname>( message and just use [connect( message to connect to ws://127.0.0.1:5678

and we keep the [connect <protocolname> <protocol dependant list of settings>( message to connect given protocol with given settings 
and the [connect <device_name>( message to connect to the device called <device_name>

**Comment by bltzr** [comment]
I'm not sure it's a good idea to remove the mention of the protocol:
1/ because even if we don't use Minuit so much with ossia-* apps, maybe someone wants to connect to an old Minuit app (I do this on a daily basis in i-score...)
2/ maybe we'll add support for other protocols in ossia-pd, such as DMX, OSC or others...

though, we can also assume that users shouldn't name their devices the same way as an existing (or future) protocol... 

since it's currently working this way, let's keep things as they are, and see if we encounter problems in the future

in any case, I find it good to keep [connect( as a way to get info into the Console, as this is the case for many other functions...

**Comment by avilleret** [comment]
I didn't suggest to remote the protocol specification when connecting
I was just suggesting removing the 2 shortcuts [connect oscquery( and [connect Minuit(
and keep [connect( to connect with oscquery on default port
but yes in this case, we loose the possibility to print some useful info in the console
but there is an help patch right ? 
Btw, let me know what you think and if I have to change something
