### ISSUE TITLE
when foo.x is removed, rename `foo.n` to `foo.x`

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#109]
just take the last element `foo.n` and rename it `foo.x`

**Comment by bltzr** [comment]
As discussed on gitter, I'm really strongly opposed to this, because, if it happened at runtime (eg during an automation on foo.n), that means that this would break
As a general rule, I'm not in favor of renaming things once created (except if we had an explicit rename message, which would be something else, i.e. some explicit action from the user, not some automated action, like is proposed here).

**Comment by bltzr** [comment]
sorry for being a nazi ;-p

**Comment by avilleret** [comment]
closed by 49.3

**Comment by jln-** [comment]
Julien Rabin a aimé votre e-mail
Spark by Readdle

**Comment by bltzr** [comment]
> Julien Rabin a aimé votre e-mail
> Spark by Readdle

Tu peux liker des mails dans ton client mail ? C'est beau le progrès...
