### ISSUE TITLE
[ossia-max] add support for Max's helper menu and other niceties

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#116]
as is the case e.g. in Jamoma

![helper_menu](https://user-images.githubusercontent.com/113982/28576039-fc2f174c-7152-11e7-921b-c9e99600abd1.png)

maybe @theod can help here ?

**Comment by bltzr** [comment]
such as https://cycling74.com/sdk/max-sdk-7.3.3/html/group__attr.html#gaababb47839dc4396bddfbf8149214e21
and CLASS_ATTR_ACCESSORS and potentially other things...

maybe @theod can help here ?

**Comment by jcelerier** [comment]
found how to do it : Max uses the maxref.xml. So I added the files here: 

https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-max/docs/ossia.parameter.maxref.xml

ossia.parameter can serve as basis for the other files which are bare-bones.

Also instead of adding the aliases manually in the code, they can be added here : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-max/init/ossia-objectmappings.txt
