### ISSUE TITLE
[ossia-max] problems with ø.param

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#129]
- [x] when using Vecnf's, only the first value of the vec is used, and copied to all n values
- [x] nothing comes out of the dump outlet when pressing dump
- [x] all values are reset to 0 when dump or bang is received, or when a value is received from the network (e.g. from i-score)
- [x] only one tag is declared (only the first one is visible from i-score or when dumping attributes)
all of this can be tested from ossia.parameter.maxhelp with the bar param

**Comment by avilleret** [comment]
for point 3 about all values are reset to 0, this is a parsing issue, `dump` message is somehow transformed into current parameter type (for instance float) and then we have 0 (I don't know who and when decided that `dump`is 0 but it is like that)

and that's why I was suggesting to add another inlet to pass `dump` and other special messages (like `namespace`) and I heard some loud protestation so I will not do that
but I do think that this is a problem to have some reserved words

**Comment by bltzr** [comment]
> I do think that this is a problem to have some reserved words

that's a very common case in Max/pd externals, though, isn't it ?
