### ISSUE TITLE
[ossia-pd] ossia.remote does not output full address

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#155]
When using some regexp inside ossia.remote address (ie foo.[0-5]/bar*), remote only send the last node of the address. In that case: 'baron', and not foo.*/baron as it should

**Comment by avilleret** [comment]
instead of returning the full address would it be acceptable to return the part of the address that match the pattern

for example [remote foo[1-5]/bar*] will return `foo.2/baron` when receiving a message from `whatever/bull/shit/foo.2/baron`
on the other side when using remote with absolute or global address the full address will be returned.

what do you think @jln- @bltzr ?

**Comment by bltzr** [comment]
I would be for returning the full address as expressed in the remote (with the relevant regexp'd values)

**Comment by bltzr** [comment]
@jln- too

**Comment by bltzr** [comment]
i.e. yes, [remote foo[1-5]/bar*] would return foo.2/baron when receiving a message from /whatever/bull/shit/foo.2/baron 
(the leading slash is important here)

**Comment by avilleret** [comment]
not sure about the leading slash but I got the idea I think
