### ISSUE TITLE
[ossia-max] ossia.model bufferizes input messages ?

### ISSUE THREAD

**Issue by jln-** [OSSIA/libossia#350]
As reported by @matcham:

> Looks like the model do not send param value immediately, but waits for a while, buffers all received messages and reorder them before sending them to parameters.
Am I right ?

----------begin_max5_patcher----------
1129.3oc2Y0zjahCD8r8uBUbl0kj.LPNkK6k8zV0laaskKYP1lDPhRHxXmT4
+9pO.aOyXXvikcRkKfQHTq2Sc2uVxee9Lu078zFOvG.+KX1ruOe1LSS5Fl08
7LuJx9rRRioadY7pJJS54aemjtWZZ+ocTFngxxKXaU2qoBhjlCpnMMjszFeP
gD7DW7kF.oAP2WSyTuteTJKXzLdKyLTAcMxZq3sxRpzXXXWqMxCkTiE6+3Zh
LamxpqDpwzBELLYAzGfhP1aP8sv3EPv+08QE4lwfu9y+ANz6jEKX8FDoa6Gy
mqu3OQxoCsuhbpNrplHHUTIU.P3.uKBQz0.wkgFnkfM2PFfhwCfPb+.Ysl7P
M0NJddG6esfpV9jDYAmctcBLFPSd9.X2kiezyXLraYLtbGU72GoszzT2QacN
FgvQoM3MPaV6fVdenMF8I0L7UrlZxTqBAUweRGvUnHK6Xv.BNJWgRl.WcywW
Ck7YwhEMJ2DfZsnsb.necIPv13Jn4VRpA5vAf9w7GC3KfQVpKJ8scFbIqjWr
YCUndCfKxoBEIcw7sXGPWV+bqSergyBBFfsBbV11ACBJXtvGHHvHhfSMqXAo
i49m3LPstUJ4LGD8FDEXWGrQwg8WuzzOZvf20D1VGF.eUo68ACoaNA+2qiqB
O49hVZVo0z1knp3qMOG9NVGgggFVmz0zjUP.gWDokPiFilV9HnogR7QTRfaD
7JfrPIJH4l69.gpcdU4Aea9PPQiRv3qTQipNU0Wc6YLPvHM0DDay2mfFS1.i
t6kcp7PbTYSAo1j51x.Q1HknyQ1FNS1T7MyHErbQBJFEzahb06TUlTRxnma4
yUEReD9KCHX7sRvVAusFfuLSguNlxJTjZ0BCGsnoQRl36Vj2VslJb.7BwwVg
DbuGvvvK8z3zkbZEkQVaMBbLj6XUGmg9tE2tx5GG8nneYf+kc64MMEjEmzSd
sTxG0yKfpZJvGyoaHpRqGNcx6xKBhrYUFMJI78Djbe4o5wnnA2e+6wUK1PTA
iu+9feIXnJdNsDnp9lKJjG9ze9Oexc6AcoU2Id7i4nebx3kbg86gKP3nvT8N
thSWBiSz+JIMDgT+Bc13bO21JQJEsE8yN8S8aTwPUNQeNs+HtNddWClXB58a
Al6Rhz4T7VfFcKf1zCS4zu3rRMSKc6OmIZ3shr9wu+D3.mlX4zFYAybNAm0I
8Ynn6zEY6IaI3ixR8CxnVB6.CE+nPzxGF0EMAK8b50rkkgCFmpkS+YYXzTVE
i9YA4WL6NZY3MY4vIX4TG3NELEDF4B+1IEJpgDx0b4jBYtOKiZsi2zzgtfdm
Rt6fWYHq5DotVeVFcc1XCkh7msEBE6adrfYez7Wr4Inesnu+glVHBkHqTov1
Jrxu6WZq91SWbmfoDzsgiJzMuSl9EJhLUgwlO8uHU7JxpcEaUPe6NIMeEWn1
XS2wT30Ut7yoDRVFkIOq9Mj8zxi5N2bSEaVn62Qs5C39k0K3UoF4h9UdMCM+
Gy+e.tu8rHA
-----------end_max5_patcher-----------

**Comment by avilleret** [comment]
In fact everything is bufferized because Max is not thread-safe.
But this is a good question, so I'm gonna to try to answer it as clearly as possible.

Network callback happen in a separate thread (i.e. in another process than Max itself that runs in parallel).
Sending a value through an object's outlet from another thread than the main Max's thread is crash prone. And believe me, crash happen :-).

So we put everything in a queue which is dispatch on each tick (that's why there is a `@rate`attributes, it defines the polling period).

So yes, technically when you send  `[set foo 33(` the value is pushed here :
https://github.com/OSSIA/libossia/blob/e44a3a7b68c38bacf789990cfe1775ec48b8ffdd/OSSIA/ossia-max/src/node_base.cpp#L199
and then all nodes are notified thanks to a parameter callback here : 
https://github.com/OSSIA/libossia/blob/e44a3a7b68c38bacf789990cfe1775ec48b8ffdd/OSSIA/ossia-max/src/object_base.cpp#L45-L46
and then the value is added to the queue in the `ossia::max::t_matcher::enqueue_value()` function with some processing to filter according to unit for example.
The `ossia::max::t_matcher::output_value()` is called periodically with a internal clock in each object.
This clock tick is driven by Max scheduler, so it is safe to output the value now.

Easy, isn't it ? 😆

**Comment by avilleret** [comment]
in your example, the internal clock of the two parameters are not in sync, even if the rate is the same, there is no guarantee that they will be processed in the same Max tick. So the order is currently undetermined...

I know this is an issue.
And now starts the headache...

The first solution that comes to my mind is to have a global clock, at least per device to pool every parameter in the same, so that, the value will be output in the same order as they come.
But then we loose the benefits of `rate` attribute.
Would it be an acceptable compromise for you ?

(I'm already hearing you crying "nothing will be worst than current behavior !" :-) )

**Comment by avilleret** [comment]
I'm curious about what @jcelerier think about that ?

**Comment by jcelerier** [comment]
https://en.wikipedia.org/wiki/Garbage_in,_garbage_out

basically whatever we could do would just be trying to fix up max (which we can't really do anyways) so any "solution" will have downsides ; what matters is finding the set of downsides that makes the most people happy :p for instance the global clock besides of nullifying the `rate` would also certainly induce worse performance since every value would be pushed in a "spike" which would certainly overload whatever is running in max.

about this issue, more generally, I'd say that it's the expected behaviour given that there is a rate attribute (else what would it mean ?). Of course if it's a longer bufferization (can't check right now) that would be a bug. And if you want enforced synchronous behaviours... well you have to use synchronous environments (so not max).

**Comment by avilleret** [comment]
one option would be to mix the two :
- keep the rate attribute to output value as they come
- trig a dequeue on each children of an `[ø.model]` (or whatever that inherite from `ossia::max::node_base`

And yes, if there are lots of values then this might hangs max a while and possibly make audio glitches, then we could use the ugly `[deferlow]` object :-)
I think it's worst a try, it should work in most case, then if it appear that this is still an issue, people might consider pivot.

**Comment by avilleret** [comment]
this behavior have been implemented in 4acceda9aad1ebf8aef2813619879e41b2dd8e6f and 887fa763d6a1c7a2d1a42e803b12b42648083f37

**Comment by jln-** [comment]
Thanks for this detailed explanations @avilleret ! I get it.

Then, out of curiosity, does that mean that in Jamoma, this _problem_ was dealt with using a general Jamoma clock (I tried the same situation and from my quick test, messages order seems preserved). Just curious.
