### ISSUE TITLE
[ossia-max] crash when changing hidden attribute from the remote

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#364]
<pre><code>
----------begin_max5_patcher----------
612.3oc2V0ziaBCD8L7qvxmoQ7QfP5odt+EpphbfIIdEXiLlsY0p8+dsGCo6
tMARhXaU6Ea4gwyadC9M1O66Q2JOBsTxmIei348rumGZxZvqesGslcrnh0ht
QYZspiSCbextBMefWVBhAyhtZYmtBz3dh5s1vzEG3h8aTPg1gY1pEgAj7b6X
b5ZbJdQH468agWhQWt8gOEGND8V8SU.ZevhCL8SMfKrT5oHXREt3TlXs8huu
cH3JIr.9gA9AjzvQL0oMJtPSTPsTCmm1gWl1Q8TMLxNsJcLdGkeYd+QQNkgF
.gUVp.iimkcwiwNjPQY3T9xQYW1s7WM3h+YiuCxuqRZhwMSO2Y1H2TZ3nra4
Pz2IU0LL.YWjuMLEqFzfZCHXaceLbrZwVlX+G+IcYaKmsvcRmrSJOeAKYxBV
RhcZ8nh7za8zPvrp0m4laNccJR+jkIiQ7U+cZtcuR.jYIYQSKAx+WRAbmki9
6uVeEkir+aZHbJ4r8DHewTMXUUaZY6.Rz8dfJwU6BGuo57biwqKHnGzJt38u
EBSUq82VkZkcphAL5kujekrkPqlKXZtT7Jehb9b1+CWKNY+gvwzGlDOENYyD
PSRnky.P1mONIRoy.PXYIZJJkOGHcEL52wwcVm0z7HnZ6cFgvn8ePhW3sJ.W
xEtk3U6TE7Hev+knElxHi0FMbmxICOl4duCsVVBJg4lTmNyPN+d456zWBSKD
bqekUKqYaNv2aX99CZnbiTY5l0+1ZC61w5pzushvJJ.gtPV4xSyKOs8MBWjZ
GrO4XwIpGzWYUlM799FzZSjwbMruB4+h+OAp4OPc
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
with the pasted patcher, it also crashes when changing it from the param's attrui
just saying...

**Comment by jln-** [comment]
Anyway, 'hidden' is already a Max attribute common to every object. So it may be wise to change this. 

I assume this attribute is in libossia and not only in Max so it is annoying to change this in Max only. But as it is now, it seems even more annoying to keep an attribute name already used by Max.

**Comment by bltzr** [comment]
AFAIK, we can use different names in libossia and Max for the same attributes - actually, we already do that for some other attributes 
so we just have to find another names for the ossia-Max ```hidden``attribute: ```@hide```?

**Comment by jln-** [comment]
Ah ok. Then what about `@invisible 1|0` ?

**Comment by bltzr** [comment]
good for me!

**Comment by bltzr** [comment]
I just did that change and committed it there: https://github.com/OSSIA/libossia/tree/feature/invisible
not sure about it, because the attribute works (I've tested with score being connected to the patcher) but Max crashes whenever there's a ossia.remote or ossia.attribute object in the same patcher

see below:

<pre><code>
----------begin_max5_patcher----------
720.3oc2X0zaiBCD8bxuBKeYuvFgw.grm5+iUqpLjoMtBrYsMsIpp+2W+Qnk
caJA0DkFsGBfGr8adOFOdbdd9LbobKnwnef9IZ1rmmOal2jyvr8smgaXaqpY
Ze2vUxlFPXvQg2YfsFucEzHeDPlMRMfXh01m3ZzSRw2LnJESuwZbWiTA8irl
KfJYmvO7j8FaYlpMbw82pfJSvsnzzEwQnjb+MRVr6FktHF8q8Chu16AxxG9N
IcniUIqkpvrDunHOYYZVj6okwYEEgmJRoD6rNX1DcMbQMX7zkr2n1rqF7nfe
qaxNSe+hcFeY9b2knIpjLiQ0w6muvjY10BAGFie0iNfnrrvqIEzAZRRxGnII
8X3PzalKdjq4k0.9THM4SPZA7j0mdWziTq4rEN+iW1YrgQf1bJJCkTLEkgbw
4+z+nq.sccFyvkhAzKIMyyHOu5uLldzO.xDzizqn.k6pk1I4iEpHDtjIt+Xw
BYNp6WkbjPgX7qyih0.FPcKHXkAdEOF6uSpZXdDymndjbQziCG.QR7ABzoF+
Lr+iKgq9uSAOvpIeZkUSPMJtxUiQSD61L+nYgi1+aznGZ9fkfj3Qkr7SJIC8
SHBMfVytGdmJ.aackwH0U+tCT69b6DklkOHyaLYLpmcPpm7EsQ7Iw2LecZzU
iQW50UcGutD0GwitQYSC.1Di15BQ23nOxl6fYeQUMuEUJMaFeUwwyfjsJTkx
xQ2S5jTojulRRmRcFWSEj1xDPM9ioUVnPxU9n5zzPdrBxgI1R745PD9Y2eFo
+4zYdWzY+u4jV1op5+N0WPC5MmbsMvlK7ECLnS4g9bPYap.kOAb5clSBH24X
NNRjy.RoSAny.NqtP3Pl.NEmAbRtP7IaB3PeGNgkTr11GAkdem8PXSH7P3+I
XYjuIWDZR8MUfK2Tn+odKLkMKgwlhnSEVOusHT6BtQtFTBaJzP1HKxuL+Ovc
dIfy
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
could you have a look at my changes, @avilleret ?
