### ISSUE TITLE
[ossia-max] new parameter in a blank patcher do not work

### ISSUE THREAD

**Issue by matcham** [OSSIA/libossia#377]
create a ossia.parameter in a blank patcher : it doesn't work (no output)

copy / paste code below in a new patcher 

(!!! if you copy and "New From Clipboard" in Max : it works !!!!!)

<pre><code>
----------begin_max5_patcher----------
356.3ocuS1sSCCCCE95zmhHecYp+nNF7pfPSocViL0kTk3N5zzd2oIocLfxX
HM3lFEG6yI9yMGhXPotCs.+Q9SbF6PDi4C4BvF1yfshtpZg0mFnZ2VhFHNbT
iAsnhDjTqVZvJJHUVw7YIw7zE26VJRbeyxlkvedrNgQrEIzrDUhxZzUVxvY8
NHU0H48K8TAT0KR05eiI8BoaoQkxFhFBQ6avfL.DygRgZMbpP4JeqpK2bWwX
mZo8gqI.t.Gihbeh+KnVd9+.09VStETK+FQM70d0F0hvNJ3f0JEyNACNII4j
nsVpvJcqhNuS9A3W7feIsXJv7qH7EU5ZQ7j3M8x30WB3Z9O8x1eYcw+Hys5V
S0noC5ye+1tBsjT440Y4TDxYxo505S9U3S5W7IzdhllcnwNjr2h9ed1nMtsK
h8akpvV+aDvf6ji4GhHL8yNpev0ZBTrawbHTpdEZTsR+nNx47wn2.L4z4HF
-----------end_max5_patcher-----------
</code></pre>

**Comment by bltzr** [comment]
Hi Mathieu !

Is that with b18 ?

Because @avilleret recently entirely reworked the subscription system, so there might be some rough corners still…

The best way to avoid this for the future: make some tests. e.g. that check if a single parameter is created. That’s your best ally to have a robust implementation for the next iterations and avoid this kind of inconvenient

There shouldn’t be much change, but can you try on this one ? 
https://www.dropbox.com/s/2gc361k5c1kjp11/ossia.zip?dl=0

**Comment by matcham** [comment]
hey
issue still present with fresh build from latest sources (thanks Jln).
and in the one you sent.

**Comment by avilleret** [comment]
+1 for making more test
and no need to add lots of exclamation mark, assigning issue is enough and markdown is fine for text formatting

**Comment by avilleret** [comment]
it works fine on a fresh opened Max
but, try again without restart and the problem occur

to reproduce :
- double click on 377-noloadbanged_initialization.maxtest.maxpat, Max open and patcher is loaded, object added and registered correctly
- close the patcher but keep Max open
- reopen the same patcher, object is added but not registered correctly

**Comment by avilleret** [comment]
doesn't work anymore :-(
