### ISSUE TITLE
ossia apps hang while VVOSCQuery apps are open

### ISSUE THREAD

**Issue by bltzr** [OSSIA/libossia#416]
that's the case for: 
- all tested ossia apps: score and other libossia-binding implementations (tested off and Max)
- and with all vidvox osc-query-compliant apps (VDMX5b8.7.0, MIDI OSCQuery Helper, OSCQuery Helper, OSCQuery Browser)

while a vidvox app is open, all ossia-apps hang at https://github.com/OSSIA/libossia/blob/15f33db5b0cf7b98315ea42a7df0f379e01c0204/OSSIA/ossia/network/oscquery/oscquery_server.cpp#L310

That doesn't happen with other OSCQuery apps (Mitti, Vezér, MadMapper), neither when trying to quit them, not when trying to quit ossia-apps with them open.

So, I guess there's some weird interaction somewhere between libossia and VVOSCQueryProtocol.

Pinging @mrRay in case you have any clue on the top of your head

**Comment by bltzr** [comment]
also, if I force-quit my app, it won't reopen until I quit the currently opened @VidVox apps if that helps

**Comment by mrRay** [comment]
howdy-

> Pinging @mrRay in case you have any clue on the top of your head


sorry, no deep thoughts on this one- this is all that comes to mind:

- the VV OSCQuery apps support websockets for notification and bidirectional streaming- to the best of my knowledge, none of the other apps you listed support the optional websockets portion of the OSCQuery protocol (someone please correct me if i'm mistaken or that has since changed).  i don't know if this is a correlation or just a coincidence, but this is what i'd start looking at first if our positions were reversed.

- please let me know if there's anything i can do to help in tracking this down- if you need a simpler test app using my codebase than the ones i've published, or if you think something i wrote isn't behaving correctly, just drop me a line and i'll be glad to help get to the bottom of this!


cheers
: : ray

**Comment by bltzr** [comment]
> none of the other apps you listed support the optional websockets portion of the OSCQuery protocol

that's a very sensible observation, thanks! we'll look into this

**Comment by bltzr** [comment]
do you have any idea what's happening here, @jcelerier ?
