### ISSUE TITLE
dynamically map parameters across devices

### ISSUE THREAD

**Issue by michaelpalumbo** [OSSIA/libossia#486]
Just posted this on the ossia forums, and am now continuing this thread here: 

>> Thispatcher (me)
>> How might one manage parameter mappings between different devices instantiated in Max/MSP? For instance I have 2 devices: weka and lightbox. Weka has a parameter “accel” while Lightbox has a parameter “panel1/RGBA”
>> 
>> Is it possible to create a mapping between accel and panel1/rgba? I am picturing something like the “webmapper” connections manager for the libmapper protocol
>> 

> 
> @avilleret
> 10m
> hello,
> 
> it is indeed possible to do such a thing but with two devices it might be a little bit tricky
> 
> you should use the global address of your parameter when your create your remote object.
> A global address is the parameter address with device prefix.
> In your case this might looks like :
> 
> [ossia.remote weka:/accel]
>            |
> ------------
> [p some processing]
> |
> [ossia.remote lightbox:/panel1/rgba]
> I’m already using this king of mapping with ossia-pd, but never tried in Max.
> Feel to report any issue here or better there.
>

**Comment by michaelpalumbo** [comment]
It's still not clear to me how the connection is established between these two parameters. @avilleret is the mapping hardcoded? Or is it possible to have two devices, query their namespaces using an interface (perhaps built in max, perhaps in a webpage), and then send a message to the ossia framework to map the one parameter onto the other i.e. something akin to 'bind weka:/accel to lightbox:/panel1/rgba'

**Comment by michaelpalumbo** [comment]
If this currently isn't possible, I suppose I could extend the abstraction I posted in #487  to also dynamically generate "shared parameters" although I'd prefer not to...

**Comment by avilleret** [comment]
> is the mapping hardcoded? 

not at all, you should have 2 [ossia.client] objects each bound to one of your devices (`lightbox` and `weka`)
Then you can access each parameter of your client with [ossia.remote] objects.
You can either use relative address (`[ossia.remote accel]`) or absolute address (`[ossia.remote /accel]`) or global address (`[ossia.remote weka:/accel]`).
Keep in mind that the hierarchy of the patcher should reflect the device hierarchy when using relative address.
There might be an issue with global address address registration, I fixed it in Pd last month but I didn't check it in Max.
In the meanwhile, you can try to use relative and / or absolute address and connect it to the other remote with send/receive.

To check if an [ossia.remote] object is well registered, that means it is internally connected to an Ossia node, you can use the [address( message which should return in the right outlet the global addresses the object is bound to.
If nothing comes out, then the object is not registered and it is a bug (either in the patcher or (more probably) on the libossia side).
And you can send the [namespace( message on [ossia.client] to check if it knows the whole namespace of your device (namespace should be updated automatically with oscquery protocol).

**Comment by bltzr** [comment]
> It's still not clear to me how the connection is established between these two parameters. 

ossia.remote is a kind of (ossia-based) send/receive pair (a little like the sr abstraction in Max)
so the connection is established by retrieving the value of the `weka:/accel` parameter from the first remote and sending it to the `lightbox:/panel1/rgba` parameter through the seconde remote

>@avilleret is the mapping hardcoded? 

yes, by your patcher

> Or is it possible to have two devices, query their namespaces using an interface (perhaps built in max, perhaps in a webpage),

there are such interfaces [here](https://github.com/Vidvox/VVOSCQueryProtocol/releases) and [here](https://github.com/Vidvox/oscqueryhtml), and of course score also has such an interface to query namespaces and values, with its Device Explorer

> and then send a message to the ossia framework to map the one parameter onto the other i.e. something akin to 'bind weka:/accel to lightbox:/panel1/rgba'

this is something that the "ossia framework" doesn't do as such
this would require:
- either one (or several) mapping engines (score can be such a thing, though) that could actually implement the connections/mappings
- or some kind of mapping mechanism in the parameters themselves (as libmapper does AFAIK), but this is not something ossia does for now

so, probably, you'll have at least to prototype one solution or another in order to achieve what you want to do
this would also be very valuable for future discussions (we applied for a grant to hold a workshop in Montréal at the end of May, we should know soon its outcome - if it didn't work, we'll apply again, for a workshop in October, this time), in order to refine questions and specifications for designing a generic mapping system using ossia, which is all the current discussions are about across various research partners

**Comment by avilleret** [comment]
I'm closing it because I don't see a real issue there
