### ISSUE TITLE
managing multiple devices

### ISSUE THREAD

**Issue by michaelpalumbo** [OSSIA/libossia#487]
I work in a lab which has many, many tools and instruments written in max/msp. We are keenly interested in making use of libossia to expose their individual namespaces across our network. However, an aspect of device instantiation that I'm hung up on is the need to assign an OSC port and websocket port per-device. My instinct is to not hardcode these, nor to have to assign them manually, and so rather to dynamically assign an OSC/WS port when the patcher is loaded from disk.

Has anyone tried this before? I'll post an example of what I have come up with shortly.

**Comment by michaelpalumbo** [comment]
[dynamicDevice.zip](https://github.com/OSSIA/libossia/files/3004882/dynamicDevice.zip)

In the maxhelp file, you'll see that the abstraction "dynamicDevice" auto-instantiates an ossia.device in the parent patcher, names it after the parent patcher, and also dynamically assigns the OSC and WS ports. It performs these tasks each time the patcher is loaded, which means that the OSC/WS ports get re-assigned.

**Comment by avilleret** [comment]
In a recent setup, I'm using more than 10 oscquery devices over a local network.
On a computer, there are 5 pd patchers which each runs an independent device.
Each of them have hardcoded port name and port numbers. They can't share the same port number because they share on the same host.

The other devices are 5 instances of an openFrameworks application that run on 5 separated RaspberryPi.
They all share the same port numbers but the name is deduce from the RPi's hostname.

Hardcoding port numbers have the advantage that you know who you are talking to.
In the other side, dynamic port number require discovery protocol (Bonjour / avahi) to be available on the network.
One thing we talk about with @jcelerier is to choose the OSC port number dynamically when a client is connecting and pass it through websocket to the client.
But this keep the websocket port hardcoded.

**Comment by avilleret** [comment]
I'm closing it because I don't see a real issue there
