### ISSUE TITLE
[ossia-pd] build it against Purr Data's m_pd.h

### ISSUE THREAD

**Issue by avilleret** [OSSIA/libossia#490]
this is a request from @agraef

**Comment by thibaudk** [comment]
:+1:

**Comment by avilleret** [comment]
https://github.com/OSSIA/libossia/commit/70ff64962d0f8f9a3fe0a48c618379f6dbe5449b introduce a new purr-data submodule and a CMake option "OSSIA_PURR_DATA".
When you switch on this option, cmake should download the purr_data submodule and checkout the commit 6343214214dc71fe37352b8c60f5980c2f0a67a7 of CicmWrapper.

If this is not the case, checkout manually with `git checkout 6343214214dc71fe37352b8c60f5980c2f0a67a7` inside the `3rdparty/CicmWrapper` folder.

You might need to configure the build from scratch (i.e. from an empty directory).

Configure with : 

    cmake <PATH_TO_LIBOSSIA_FOLDER> -DOSSIA_PD_ONLY=ON -DOSSIA_PURR_DATA=ON

Currently there is a know issue :

     multiple definition of `array_garray'; CMakeFiles/ossia-pd.dir/src/attribute.cpp.o:/home/antoine/dev/OSSIA/score/3rdparty/libossia/3rdparty/purr-data/pd/src/g_canvas.h:155: first defined here

This is due to a bug in the purr-data header.

**Comment by agraef** [comment]
Hi @avilleret, thanks for looking into this and getting back so quickly! I'll have a look at that double declaration asap, hopefully it's a minor issue.

**Comment by jcelerier** [comment]
hmm, looking at it it seems that g_canvas.h cannot be included in more than two files.
A solution would be to declare the variables (`t_class *preset_hub_class;`, etc...) as extern and give them an implementation in a `.c`. I'll make a PR on purr-data for this.

**Comment by agraef** [comment]
Hmmm yes, I have to agree that there's clearly something wrong in our header file there. Your suggested fix seems sensible to me, but I'll have to find out how and why that got in in the first place and then commit the fix upstream at https://git.purrdata.net/jwilkes/purr-data.

**Comment by agraef** [comment]
> where are externals supposed to go with purr-data ?

On Linux, the global installation path is usually /usr/lib/pd-l2ork/extra/. Locally (in the user's home directory) they go to ~/.pd-l2ork-externals. I'd have to look up the details for Mac and Windows if needed.

**Comment by agraef** [comment]
Ok, I gave this a quick whirl now with the example from https://github.com/OSSIA/score-user-library/tree/master/Scores/Examples/UnifiedExample-Max-pd-SC, and it seems to work fine!

The Tcl/Tk property GUIs of the ossia.* objects won't work in Purr Data, of course, since Purr uses JavaScript for its GUI. Maybe I can get one of the cs students in my course to rewrite the Tcl/Tk stuff in JS as his homework assignment. But in any case the lack of the property GUIs doesn't seem to be a major impediment, since presumably all the options can also be set as creation arguments of the ossia objects.

I'd suggest to keep this issue open until I get @jcelerier's changeset into the upstream Purr Data repository (at which point of course the rev. of the purr-data checkout in the libossia submodule will have to be updated accordingly).

Again, many thanks to everyone involved for getting this to work so quickly!

**Comment by avilleret** [comment]
concerning the properties page of Ossia object, it's not very useful so don't worry for that.

ok for letting the issue open until upstream repo update

**Comment by agraef** [comment]
Submitted upstream as https://git.purrdata.net/jwilkes/purr-data/merge_requests/281. I'll let you know when this gets merged.

@avilleret I think that it would be nice to at least conditionally disable all the Tcl code in there when running in Purr Data, because it causes a bunch of ugly "legacy tcl command" warnings in Purr when loading the external. Are those Tcl commands set in the ossia-pd code somewhere, or does CicmWrapper generate that stuff automagically?

**Comment by avilleret** [comment]
> or does CicmWrapper generate that stuff automagically?

kind of, but iirc there is a line to remove to disable the properties page
i'll take a look at that asap

**Comment by agraef** [comment]
@avilleret Thanks, if you could at least point us in the right direction, that would be much appreciated. :)

Also, I'm curious: Do you remember from the top of your head why the g_canvas.h header is needed by CicmWrapper in the first place? Maybe it's something that should better go into one of the "official" headers like m_imp.h...

**Comment by agraef** [comment]
@jcelerier's changeset has now been merged upstream in https://git.purrdata.net/jwilkes/purr-data/commit/f68e8b878a618c00de8f42cfc1c69fae5afabc00. It would be nice if the submodule hash could be updated accordingly, and the purr_data branch merged into master, thanks!

**Comment by avilleret** [comment]
I think this is the `eclass_register(CLASS_OBJ, c);` call at the end of `setup*(...)` method like here : 
https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-pd/src/parameter.cpp#L313

putting this under and `#ifdef` statement should be enough to disable the properties page.
I'll give it a try on the purr_data branch and before merging into master asap.

**Comment by agraef** [comment]
Ok, I'll give that a go as well and see whether it gets rid of the warnings, thanks.

**Comment by agraef** [comment]
Yes, that removes the properties from the ossia objects. But I still get some 1800 warnings from initialization Tcl code being sent to the gui at startup. This comes from the code at ecommon.c:41-114 (in the epd_init routine) and eclass.c:901-1006 (in eclass_properties_dialog, which in turn gets invoked in eclass_register; there are a bunch of different calls to the latter all over the place, so just disabling that single line you mentioned doesn't really get rid of all the messages).

I can just disable all those sys_gui calls directly in epd_init and eclass_properties_dialog in the CicmWrapper source, which gets rid of all the legacy tcl warnings in Purr. These calls won't do anything in Purr anyway (besides spitting out those warnings). Then we can also just leave in that one call to eclass_register in parameter.cpp since it doesn't do any harm any more.

Now the messages in Purr's main window end with:

~~~
already registered ossia.view
Welcome to ossia library
build SHA 5f0a0695
[2] already registered synth
New 'oscquery' protocol with OSC port 1234 and WS port 5678, listening on port 1234
~~~

Which looks good AFAICT.

(Those already registered classes might indicate that these classes get created more than once somewhere in ossia-pd, though. Vanilla Pd doesn't check for that, but Purr does, so I only see that warning in the latter. Might be something worth looking into some time, but in any case this is unrelated to the present issue. I also get these warnings when leaving in the Tcl code, but overlooked it before due to the gazillion of legacy tcl warnings.)

**Comment by agraef** [comment]
So it looks like we can't just get rid of all the warnings without touching the CicmWrapper source itself and introducing some conditionals there (in epd_init and eclass_properties_dialog), right?

**Comment by agraef** [comment]
For the record, these are the exact changes I did to CicmWrapper to get rid of all the warnings (of course, those `#if 0` would need to be changed to some conditional symbol which gets figures out at configuration time).

~~~diff
diff --git a/Sources/eclass.c b/Sources/eclass.c
index 17f6b0c..9eea0c3 100644
--- a/Sources/eclass.c
+++ b/Sources/eclass.c
@@ -859,6 +859,7 @@ static void ewidget_init(t_eclass* c)
  */
 static void eclass_properties_dialog(t_eclass* c)
 {
+#if 0
     int i, j, lenght;
     char buffer[1000];
     char temp[1000];
@@ -1004,7 +1005,8 @@ static void eclass_properties_dialog(t_eclass* c)
         }
     }
     sys_gui("}\n");
-    
+
+#endif
 }
 
 
diff --git a/Sources/ecommon.c b/Sources/ecommon.c
index edb02aa..c433c5e 100644
--- a/Sources/ecommon.c
+++ b/Sources/ecommon.c
@@ -37,6 +37,7 @@ void epd_init(void)
     s_double        = gensym("double");
     if(!epd_symbol->s_thing)
     {
+#if 0
         // PATCHER MOUSE MOTION //
         sys_vgui("proc eobj_canvas_motion {patcher val} {\n");
         sys_gui(" set rx [winfo rootx $patcher]\n");
@@ -112,7 +113,8 @@ void epd_init(void)
         sys_gui("append col [format {%4.4x} $nB]\n");
         sys_gui("return #$col\n");
         sys_gui("}\n");
-        
+#endif
+
         epd_symbol->s_thing = (t_class **)1;
     }
 }
~~~

**Comment by agraef** [comment]
> Then we can also just leave in that one call to eclass_register in parameter.cpp since it doesn't do any harm any more.

Scratch that. That call still needs to be disabled to get rid of the properties menu option in the ossia.* objects.

What about all the other calls to eclass_register in the ossia-pd source (attribute.cpp et al)? Can these be a problem, too? I guess so, because the ossia.device object in the sample patch still has a Properties option spitting out Tcl code even if the eclass_register call in parameter.cpp *is* disabled.

**Comment by avilleret** [comment]
> What about all the other calls to eclass_register in the ossia-pd source (attribute.cpp et al)?

Yes, of course we should remove them to get rid of warning in PurrData, I just point to ø.paramete's source as an example.

Btw, I was thinking about removing CicmWrapper dependency for a while. It's not that easy, we should rewrite big part of the code. 
In the meanwhile, we can tweak CicmWrapper code as far as we need since we're using our own fork in libossia.
So it's definitely possible to add some `#ifdef PURR_DATA` somewhere.

**Comment by avilleret** [comment]
So i merged the purr_data branch and fixed most of the thing (sysgui call) but not the ossia.view already register I don't understand where it is first initialized.

Here is the commit that closes this issue : https://github.com/OSSIA/libossia/commit/2c8869a040a7ef738049fd820d9a1615a655ec4b

**Comment by agraef** [comment]
Hmm, this doesn't seem to work. :( I just built the latest revision (rev. 4ec266412) and installed it, and now the test patch just hangs, i.e., after launching `purr-data -lib ossia fm-example.pd` the patch opens and then immediately Purr Data becomes completely unresponsive (just printing `watchdog: signaling pd...` on the command line) and I have to kill it.

**Comment by avilleret** [comment]
oups, could you try this commit ? 2c8869a040a7ef738049fd820d9a1615a655ec4b
we do have some trouble with networking (with minuit and zeroconf) that might freeze pd

btw where is the fm-example.pd patcher ?

**Comment by avilleret** [comment]
on my side I test it with purrdata and device-example.pd / client-example.pd (from [here](https://github.com/OSSIA/libossia/tree/master/OSSIA/ossia-pd/examples))

**Comment by agraef** [comment]
Unfortunately, that revision locks up after loading the patch as well. :( If you don't see it then that's weird, but may be down to some race condition playing out in a different way than on my system. For me it happens every single time; that's on a Lenovo X1 Yoga (4 cores/8 threads) running kernel 4.19.36.

I can't help noticing that since rev. 2c8869a040a7ef738049fd820d9a1615a655ec4b there have been a few unrelated changes since the original purr_data branch got committed on April 17/18, so I guess that at least one of those must have been bad. Maybe it would be better to move those minuit/zeroconf-related changes into its own branch until it's better tested? I suspect that the bug might be lurking there somewhere, as it was committed around that time and it uses mutexes. It's hard to debug this on my side, though, and using simple bisecting won't let me track this down either. What I can try is to go back to rev. e3939d67bb6e1b9d8d67bc59440df14d18d78b9a, and cherry-pick the subsequent purr-related changes. I suspect that this should still work, and then one might go about pulling over the other commits from the master branch up to rev. 2c8869a040a7ef738049fd820d9a1615a655ec4b one by one to see where exactly it starts locking up.

The example I used is from here: https://github.com/OSSIA/score-user-library/blob/master/Scores/Examples/UnifiedExample-Max-pd-SC/Pure%20Data/fm-example.pd along with this score: https://github.com/OSSIA/score-user-library/blob/master/Scores/Examples/UnifiedExample-Max-pd-SC/max-pd-sc_unified_fm-example.score.

**Comment by agraef** [comment]
Yes, as I suspected rev. e3939d67bb6e1b9d8d67bc59440df14d18d78b9a with just rev. 02d31a43ed1f9ead103cfc29d708661d55992ca1 on top of it works just fine. So the problem must elsewhere.

**Comment by agraef** [comment]
Well, I it looks like this may have been fixed on the master branch since I've last tried. To be sure, I'm trying a fresh build from scratch right now, keeping fingers crossed.

**Comment by agraef** [comment]
Jonathan's gitlab seems awfully slow today, I'll try again later.

**Comment by agraef** [comment]
Looking good now! :)

Would be nice to have ready-made builds of the purr-data external for Mac and Windows, though. Any chance that you'll include these in the next release, any time soon?

**Comment by avilleret** [comment]
cool that it works now ! do you have a distribution system such as deken on PurrData ?
if yes we can upload binary direclty on it
at least there will be on our github release page as soon as the CI pass, i'll try to have a look in the next few week

**Comment by agraef** [comment]
> cool that it works now ! do you have a distribution system such as deken on PurrData ?

Nope, unfortunately not. You see, pd-l2ork/purr-data has always taken the everything-and-the-kitchensink approach, so we try to include just about every useful external that's out there and thus there's much less use for a package manager like Deken.

> at least there will be on our github release page as soon as the CI pass, i'll try to have a look in the next few week

That would be great. Then I could just point the students to the release page and show them how to get it installed.
