### ISSUE TITLE
[ossia-max]rate attribute doesn't work on ossia.remote

### ISSUE THREAD

**Issue by vincentgoudard** [OSSIA/libossia#541]
title says it all.
Observed in the ossia.remote help patcher #

**Comment by jcelerier** [comment]
@bltzr or @jln- do you think that's a solvable-in-Max thing ?

**Comment by avilleret** [comment]
what did you observe exactly @vincentgoudard ?

`@rate` attribute meaning has changed since it was introduced.
At the very beginning each max object has its own polling clock which could be cadenced at the `rate` frequency.
Then for performance reasons, we kept only one global clock polling all parameters values at once.
I think it's still used by score to set the data rate when playing. @jcelerier could you confirm ?

So now, in Max, `@rate` has no effect but it is passed to remote software like Score and could be implemented there.

We could implement it again in Max, but then the default rate should now be 0. not 10.
And instead of a polling clock this should drive a speed limiter, to get a new value at most each rate ms.

What do you think guys ? @bltzr  @jcelerier @vincentgoudard

**Comment by jcelerier** [comment]
> I think it's still used by score to set the data rate when playing. @jcelerier could you confirm ?

that was the idea but so far it seems that people have managed to get by the simpler rate limiter - it could likely be done if there was enough demand but not really a priority atm

**Comment by avilleret** [comment]
> people have managed to get by the simpler rate limiter 

This sounds reasonable to me. But then the max documentation should be updated.
