### ISSUE TITLE
[ossia-max] [ossia.remote] get range is not shown when @type 'string'

### ISSUE THREAD

**Issue by maybites** [OSSIA/libossia#549]
consider the following patch:
<pre><code>
----------begin_max5_patcher----------
1476.3ocyYszjahCD9rmeETbIW75Ewa1SSprm1qI6kMUJWxfrsR.DkjXlIap
7ee0K.AF73YrS1bXnvcKg5Ge8mZo4a2sxcG4IDy04Ob9nypUe6tUqThjBVY9
8J2J3S4kPlZXt0nGI69r6ZsJN5ItRbCEWy6jV2VQZ4kHtZJdFoMPd9Qb8gsT
TNWujQfvMdqc.ffMIAgfXPPRbVT.vOZsSfuTku3oymLeAbgZsDq+uA.VKFtt
as.RYe+t6jOVegdTEhwfGPm3RGPbGJrdPyX2BrraEDpbqfH4ynrS7C8Wg+0F
jd7tty5hdy5h9uBWbgjFgwvvMTTEgibXs6pHEnxeWjH21.ovp486fm0uSBTI
0zKwwWa9at.PVmAjSJIT8L71H.GgYqEujjE6kjJeKMKD.DuArVpqFVbSA59o
AuRfd3uv3bferzzC8tJbdvMCl2VgpaOOpcOolWCqTFj6aoXXo6x9WV7hIsLs
2FbNuUATNAeyQUFBW2+AQIRsqkO965g2+SBq+8OPQC+3csPt0bdGtNe3WuGg
GF46wHNZXYk98dXNxFmZixBGBChJewToaQ0vckilf7ivv+qRFPBn+wVpMO8D
iSkYoWGCkNipIn78huRBpj+WIn1o7ODsyHd.id7ALCuCWh4e0tzkreOCw6rO
OoEMXGkj7ufJJnvCrbJorzNgmWhy+B+Hkzd3nsbMz33oSPq3gSUr6fL6oJr6
jPnEHp8XlmMEUsCU7LDQgppQPRxF+oEpQQJO1WTvlDGkFjF6G3EFmlDM6dty
xEMhXWayq5SJhxBrvkQTFlTaYmqbgMMVhWYMEYl7yZDS55dQ3ZsHPuHJRlP0
yOrWJjJ7etv4aoZdrmh6JekeFQblV2h6gUJLkwjTnGI+GqwPFn.YcpGhnoQp
ckBiUkJwZJ9vTKfiLmpwNVgHAVqAUiqaDjVnZNjaL9d0En8v1R91QTI9alU+
D9pwJmkDek6AJtfTKMhQoBo3tkSrukpwL4yAmQMhZXyLSV.LDwkETxDNYKaG
jpJ8Jsg3BpLBobrp94Uh1yMpav00ShhbRyxJo3CGOyb2QDJqN22VogsssVqc
q.Tv2xfOLNZygkkFl4we9mf03JHGww5TfuWuxSHF.i07vLZJDf7bzi3Btliw
FLHFNtoCD41mkKvGPL9XYbAA1XIL9W0AcKQscrlaE6C2TB4SFfn7.y3rijGY
lA1AzrC.CGYxtn1lvdj7y1H1387.1RmsQrEawTAp8S.Zr8IMU9LcjMkILZhg
LoyrUc6WY3WdkghQ67O2t+8si3zerDm6M7.N.m6kthTky8pVXEh.dN2K12pw
QTGbb4no+yDM06ZD.zM35cgQy0mIhltXDEbCinmCbo627UhuLjlAIpi1Fbkv
q3eJvqyELT8a+Zq0z3AO+aSsV3OkfQNoRb9H9rAiObDybT8W6HdQ0xUApPTX
4.c5XL23rb7x6RvNgl3jtsauIgKosLpO5ft9nCBi7xT8QGjnkAlL2Y5I+GaU
14hku0DHkabT37ltCt7lqL5oOvYFPyxub..jYuPi5yJci2OifyKfT29vbC75
6osLdakgcWOlNBdIGlin18VPxanzh02hQVvMfj228WhHrFA1A8tRN+LCyu2U
RyAdQwlgVyKw0K0vkxlk5mOnwHsz7N6xjdbFa9hdL4359Cp7wdFYQqDe5hRY
uTaH9BsAis9CwFRuPaHZw3fQnVh4lKTevwoK8EYL07LWmwIlUfsYsfIkLDVN
4BStz0IzjeujExLlJbQCQznowy.gQahDeiv3Suav3zmQUrtuAuntebktizR8
eFuI7FD1RtfzS3sXgj+qOd1UJ6FrPYWPjS9uZZxBoA5SteG4ZL4dclbmNmde
NKeWNSuGG0c3nOR6jhq9aB4ufUjJ31i3CBW+vQt3j8DqK1u65SFGRf44hFYr
Z7Bnufvn05qJDLfNWaBsTwDld1Z2JwWVYqdVQnEtto699c+G71a0q
-----------end_max5_patcher-----------
</code></pre>

when pressing 'get range' I would expect the list of strings that correspond to the @range attribute from the [ossia.parameter] object. but the result is:

print: address submodel/string_param
print: range \<unknown> \<unknown>
print: min
print: max

I tracked down the output to this line: 

https://github.com/OSSIA/libossia/blob/3a1fdddf328bc6ccc90e640baa2db5b6b55a6ee6/src/ossia-max/src/parameter_base.cpp#L544

but was unable to figure out why it is not working.

**Comment by jcelerier** [comment]
@avilleret do you have an idea on that one ? the range seems to be initialized in `void parameter_base::set_range()` but I'm wondering if this isn't the case only if it is set from max through the range attribute, and not from within ossia itself ? 

thanks for tracking that down @maybites !

**Comment by avilleret** [comment]
@maybites could you check out that PR : https://github.com/OSSIA/libossia/pull/555 ?
it should fix your issue

also thanks for patcher, I modified it to integrate it with other automatic max-test.

**Comment by avilleret** [comment]
@jcelerier the invalid data is due to several things combined...

first in the @maybites example the remote object is created before the parameter default value initialization 
during its initialization, the remote pull the parameter value to output it
despite the parameter doesn't have a value yet, https://github.com/OSSIA/libossia/blob/feature/max_thread_safe_test/src/ossia-max/src/remote.cpp#L341 returns an empty string (which is a value even if it's empty)
then hence the parameter have a range and a clip 'both', https://github.com/OSSIA/libossia/blob/feature/max_thread_safe_test/src/ossia-max/src/object_base.cpp#L228 filter it out and invalidate the value,
then the object receive an invalid data

I fixed it just by ignoring the invalid data with 78b1fa52 
But I though it was worth notifying the behavior I found weird (empty string instead of no value and the filter behavior)

**Comment by maybites** [comment]
it looks good, seems to be fixed.
