### ISSUE TITLE
[ossia-max] v1.1.0-a4 - opening ossia.model maxhelp crashes Max

### ISSUE THREAD

**Issue by jln-** [ossia/libossia#638]
As title says, opening ossia.model.maxhelp, either from Finder or from ossia.model contextual menu crashes Max.

Crashlog below.

https://gist.github.com/jln-/d7cbc8bda570b0073811c82e43d3e1fe

**Comment by avilleret** [comment]
what is this thread 33 ?
thanks for the report
unfortunately I can't reproduce it here yet

**Comment by avilleret** [comment]
could anyone else have a look at this ? @bltzr ? @jcelerier ?
I can't reproduce it on my side

**Comment by jln-** [comment]
Just to let you know that I tested on my old computer (same Max version and OS) and I get a crash as well.

(FWIW, I also get the broken init thing discussed over Gitter).

*head scratching*

Pinging @matcham as well.

**Comment by avilleret** [comment]
a similar crash happen to @evanmtp  with OSX 10.13
[Uploading ossia_10_13_crash.txt…]()

**Comment by jln-** [comment]
And related crash log

[crashlog2.txt](https://github.com/ossia/libossia/files/5621781/crashlog2.txt)

**Comment by evanmtp** [comment]
Here's another one made with a debug build:
[ossia_crash_10_13_evan.txt](https://github.com/ossia/libossia/files/5622614/ossia_crash_10_13_evan.txt)

**Comment by avilleret** [comment]
Thanks for the crash log.
I can reproduce it at the end but only with override enabled.

**Comment by avilleret** [comment]
This is due to a threading issue in overdrive mode
In overdrive, the scheduler runs in a high priority loop while UI runs in the main loop.
This is well explained here : https://cycling74.com/sdk/max-sdk-8.0.3/html/chapter_threading.html 
And this is definitely a design issue on our side that might lead to a lots of crash. 
We definitely need to fix that one asap.
