### ISSUE TITLE
[ossia-cpp] mirror doesn't get update from other mirror

### ISSUE THREAD

**Issue by x37v** [ossia/libossia#683]
I've got a failing test case here:
https://github.com/Cycling74/libossia/tree/xnor/mirror-update

Basically, my understanding of the oscquery protocol is that an update to the device should get sent out via WS to subscribed listeners. I'd assume that a `opp::oscquery_mirror` is supposed to subscribe to all updates but I don't see updates on a 2nd mirror when send updates from my 1st mirror.

In practice, I'm actually doing this with other software, I have a libossia base server, I'm subscribed via WS from a javascript program, and I'm updating both from that same javascript program as well as UDP based OSC from the commandline `oscsend` application.

Is there some configuration I'm missing or is this just a bug?

**Comment by jcelerier** [comment]
ah, I think it's a config flag that hasn't been carried forward to the high-level  api - the low-level has an "echo" flag that controls that (which was by default set to off, if I remember correctly, because it's not always possible to devise the origin of the message you're getting, thus there are some scenarios where client & server send themselves the messages in a loop - e.g. client changes a slider, messages get sent to the server, server sends back message, but by that time the client has moved the slider a bit more and it gets moved back which could be frustrating. 

Adding the api to control that quickly.

**Comment by x37v** [comment]
> ah, I think it's a config flag that hasn't been carried forward to the high-level api - the low-level has an "echo" flag that controls that (which was by default set to off, if I remember correctly, because it's not always possible to devise the origin of the message you're getting, thus there are some scenarios where client & server send themselves the messages in a loop - e.g. client changes a slider, messages get sent to the server, server sends back message, but by that time the client has moved the slider a bit more and it gets moved back which could be frustrating.
> 
> Adding the api to control that quickly.

Ha, it looks like it is already there, I just missed it!
