### ISSUE TITLE
[ossia-max] excluding parameters @mode GET/SET from presets

### ISSUE THREAD

**Issue by evanmtp** [ossia/libossia#713]
As discussed in https://github.com/ossia/libossia/issues/624 , when saving presets using ```preset save``` and ```preset load``` messages to ```ossia.device```, parameters that have ```@mode GET``` or ```@mode SET``` should be excluded. I am currently having trouble doing this either directly with messages to ```ossia.device``` or with a JSON/dict-based system.

I built a simple patch to save multiple presets into JSON files, based on the method demonstrated in the ossia overview patcher. Storing a preset entails sending a "namespace" message to the ```ossia.device``` in the main patcher, and then storing all the resulting parameter names and related values in a dict. The problem is that ```ossia.device``` returns all parameters, including ones that have ```@mode GET``` or ```@mode SET```. It seems like the solution would require a way to query ossia.device for the namespace but have it only return parameters that don't have ```@mode GET``` or ```@mode SET```.

Further, I tested saving presets using ```preset save``` and ```preset load``` messages directly to ```ossia.device```. The parameters with ```@mode GET``` or ```@mode SET``` are included in the saved preset files. As well, the ```preset load``` message to ossia.device causes Max to beachball indefinitely. Unfortunately I wasn't able to get a crash log.

Please see the attached patches (open simple_cues.maxhelp ). Tested on a MacBook Pro, macOS 10.15.7, with the latest official release ("$(releaseTag)-551bed2").

[simple_cues.zip](https://github.com/ossia/libossia/files/6005927/simple_cues.zip)

**Comment by avilleret** [comment]
Concerning the `namespace` message to `ossia.device` it will always return the full namespace.
To filter it out and retrieve only some of the parameters based on their attributes, you should use the `ossia.explorer` object which includes a filter based on tag, visible and mode attributes.

Concerning the ossia preset system, excluding get and set parameters has not been implemented yet.
And last but not least, concerning the infinite beachball, it is caused by the loop over ossia.parameter. Use remote to make easy loop or add a `[prepend set]` between the outlet of ossia.parameter and the number inlet.

**Comment by evanmtp** [comment]
Thanks @avilleret , good point re: using ```ossia.explorer``` - I'll alter the preset thing to use that instead of ```ossia.device```. Also sorry about the false alarm concerning the beachball, those loops around the ```ossia.parameter``` in that patch were a mistake on my part.

**Comment by avilleret** [comment]
@evanmtp this issue was closed because ossia-max preset now includes only parameter with mode `bi` (I fixed it few hours after writing my first comment)

**Comment by evanmtp** [comment]
Amazing, thank you!
