### ISSUE TITLE
[ossia-max] @mode SET/GET/BI is broken in v1.2.6-rc2

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#753]
Seems like everyone is BI in [v1.2.6-rc2](https://github.com/ossia/libossia/releases/tag/v1.2.6-rc2).

<pre><code>
----------begin_max5_patcher----------
615.3ocyW1zaZCCFG+bxmBWelg7KIgjcZpRSU8L61TUkI31lJhMxwvnqpe2W
rMglMnHWpGoGHH+DS96eOuFdNNBNStg2.AeE7SPTzywQQVSFCQaWGAqYaJWv
ZraCVJqq4BMbj6dZ9Fs0NeMW8jTvAUMfKuFbQ2Fplausb1ieglzYTrptRrfq
sOR7qFkqzcVQastjoKenRb+sJdo1cPoIzwnQ.LNw7UA1bkfFi.2X9IuDGatL
xSdtagrU3tCl6.neZI2IEDNB.mwD2CA2rOPjIvcmREqlq4pa4B1rE79DbmTU
yrG8L+wm713mljYwOM27UJxhOYHvOeXv2xMtfD.7E7e0RxdIyxllJ1XEuVp4
fxGjWd8uOpKx94PtHJ9cjxSeanyPndPiwE++ndWrbK3fuUKmyaqoOtG3fzSf
AIj2QuKimfJFtTdxPjxSnNhc88FxJd5ffehi3IomuJ9q35SqhmjDlJdRAsGz
muJ9Vv2Vwe02+w6ujmjFlRdRQZuTdBd3x4wCxTthOGi3wngC9y4.9omZ4dVf
luS6OdmdtJ1mtqXe5oTriCz3cZ+o6j7CBuUe3hJw+92UrOPi8+1izHWoJ6Hn
azM.sCi47Fckfoqjh9aJ0soC508VoTeThDBkx8PIy6f9wUZhOJEDlR7w6QCf
RYdHjoA3GVHrOgoPDk5B0G22kGBk7pZZRHxGn9nTRHBSHOTJKDB4S5v9QIWK
P1xkq4pls61pQa6+GkJyx7Q1kUB2RaSWnhutpa+1lyPlpsGrtsA7Jk8bA2j4
dsUnYXfRrpxt2XCcsRZGsHZGazrj4.wNAJ9k3+vImqSE
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
I think this is an expected behaviour : the `@mode` attribute is only a hint for the remote client.
It's up to you to connect or not the input/output of objects with set/get mode.
It used to be blocked but I think we agreed at some point that we should not block anything. 
I think this was a request from @jln- or @matcham

**Comment by vincentgoudard** [comment]
ah ok, my bad!
