### ISSUE TITLE
Code signing broken for Max releases 

### ISSUE THREAD

**Issue by jcelerier** [ossia/libossia#773]

**Comment by evanmtp** [comment]
Observed on macOs. Also Windows 10 just did a Cloud Security Scan on some ossia-max objects that I had just downloaded, so I guess it's an issue on both.

**Comment by avilleret** [comment]
@jcelerier I just had a look at the GH action log, there is nothing wrong, but the log is not that verbose though
Sometimes I experienced code signing failure because Apple changed the license and we need to accept the new term on the AppleID web portal to fix the issue. 
But usually I got an error message saying explicitly to do so.

**Comment by jcelerier** [comment]
yep but I checked and all the documents are "signed" on the apple developer portal. but it seems that some steps are missing when executing thje script, it's weird

**Comment by jcelerier** [comment]
@evanmtp can you try this one ? https://github.com/ossia/libossia/actions/runs/2033569500

I changed from zip to ditto and it seems to manage to notarize them like this...

**Comment by evanmtp** [comment]
Just tried it - seems to be resolved. Thanks!
