### ISSUE TITLE
[ossia-max] ø.remote / ø.parameter doesn't echo input value anymore

### ISSUE THREAD

**Issue by avilleret** [ossia/libossia#784]
The fix concerning #748 and introduced in https://github.com/ossia/libossia/commit/5138fc05c4fd4dca9ce96a4578b13e44bc267488 breaks the echo output of  ø.parameter and ø.remote which is a big regression

**Comment by jcelerier** [comment]
uff, what's the solution for this ? i feel that the issue is in contradictory requirements rather than code, no ?

**Comment by avilleret** [comment]
idk according to #645 this is a feature

**Comment by avilleret** [comment]
but this sounds weird to me, in my opinion, ø.remote should always output its value, but the inlet should be locked on parameter value callback to avoid feedback loop

**Comment by matcham** [comment]
Sorry, I arrive a bit late in this discussion... but looks like ossia.remote now always outputs its value, even if it has been changed by its input.
do you remember @avilleret @jcelerier when we decided to remove the direct input->output echo (it was during our last workshop last year..)
(I think it was mainly because of my request ;-)
We felt agree that there is no reason to make a remote output its value when it has ben changed by its input.
I had a good reason to make this request : if an ossia.remote is connected to a live.ui object (f.e. live.slider) the "set" value message that goes to live.slider stops Live automation.
(yes I'm talking about using ossia within Live)
When a live.* receives a "set value" message, it acts as if it has been controlled by mouse, and all clip automations are interrupted. 
Since this workshop last year, I made quite a lot of M4L devices with ossia remote connected to live.ui ; but with latests ossia versions, all my automations are broken, and there is no easy way to workaround :-{
If you really need that ossia.remote directly outputs its input, could there be an attribute ("do no echo input" / off by default) to disable this feature ?
(or the opposite :  @echo_input 1 ,enabled by default... if you really want it ;-)

thanks for considering

Mathieu

**Comment by vincentgoudard** [comment]
There is actually a good reason for this design, which is that the ø.remote will echo the value with the correct type and clipping. For instance, if the corresponding parameter is an integer clipped between 0 and 100, sending 234.56 to the remote's input should echo "100" (IMHO).

An workaround for your problem @matcham is to put a gate "à la sw" inbetween your slider and the remote.
An alternative to the echo design is to request the type and range of the monitored parameter(s) (which can become tricky when multiple monitored parameters do not share the same type/range).

The `@echo` attribute (let's keep it shorter :)) sounds like the best of both worlds.
My 2 cents.

**Comment by matcham** [comment]
the "à la sw" trick is a bit tricky, because by default leftmost outlet of ossia.remote is deferlowed, so it won't work. (unless I set all my remotes to @deferset 0, which may lead to other issues...)

@echo would fit my needs perfectly :-)

**Comment by vincentgoudard** [comment]
ha! I forgot that ø.remote is deferlowed.
Out of curiosity, is there a major reason for that? or is it just because "most of time" you would deferlow it ?
The problem that I see is that you cannot "undeferlow" a deferlowed output (which is why I didn't do it in my own implementation). But I am always suspicious about those cases that I didn't foresee.

**Comment by avilleret** [comment]
I think deferlow was implemented to avoid stressing too much GUI object with lots of messages, but I'm not sure it works like it should : I don't think deferlow was the right tool to address this issue. We'd better use a speedlim to do so.

Concerning the @matcham requirement, adding a `@echo` attribute seems a reasonable solution for me.
I'll open a separate issue for this feature request.
